# Generated by Django 4.2 on 2025-07-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image for the carousel slide (e.g., 1920x800 pixels)', upload_to='carousel/')),
                ('caption_header', models.CharField(blank=True, help_text='The main heading for the slide.', max_length=200, null=True)),
                ('caption_text', models.TextField(blank=True, help_text='A short description or call to action.', null=True)),
                ('link', models.URLField(blank=True, help_text='URL the slide links to (e.g., a product page).', null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which the slide appears.')),
                ('is_active', models.BooleanField(default=True, help_text='Is this slide currently visible on the site?')),
            ],
            options={
                'verbose_name': 'Carousel Slide',
                'verbose_name_plural': 'Carousel Slides',
                'ordering': ['display_order'],
            },
        ),
    ]
